#!/usr/bin/env bash

# Usage:
#   ./create-rg.sh "<SUBSCRIPTION_ID>" "<RESOURCE_GROUP_NAME>" "<LOCATION>" "<BEARER_TOKEN>"

SUBSCRIPTION_ID="3515a720-ecab-4ae2-9895-d4371d255dce"
RESOURCE_GROUP_NAME="test-api-rg"
LOCATION="eastus"
BEARER_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InJ0c0ZULWItN0x1WTdEVlllU05LY0lKN1ZuYyIsImtpZCI6InJ0c0ZULWItN0x1WTdEVlllU05LY0lKN1ZuYyJ9.eyJhdWQiOiJhcGk6Ly80NWNkZmYwZS04NzE5LTRlMzEtODJlMy02OTYwYmU0Y2VkNjQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xYmJjOGEzOS00YjFhLTRhZDgtOTAyZS0yZDQ4Y2QxODEwYmIvIiwiaWF0IjoxNzY1MDE3NjU0LCJuYmYiOjE3NjUwMTc2NTQsImV4cCI6MTc2NTAyMTU1NCwiYWlvIjoiazJKZ1lLajRkUDNUMVp2OVhiUGZ1cko0blg3UERRQT0iLCJhcHBpZCI6IjRjOWUzMDUxLWVjOTMtNGE1NC04YjE5LTI1ZDQ0YTVkNWIyYiIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzFiYmM4YTM5LTRiMWEtNGFkOC05MDJlLTJkNDhjZDE4MTBiYi8iLCJvaWQiOiJkNGUxZjFjMy1mMDc1LTQxN2QtYmY2MC04NGQ5YjM1YjcyN2EiLCJyaCI6IjEuQVZZQU9ZcThHeHBMMkVxUUxpMUl6UmdRdXc3X3pVVVpoekZPZ3VOcFlMNU03V1NlQUFCV0FBLiIsInN1YiI6ImQ0ZTFmMWMzLWYwNzUtNDE3ZC1iZjYwLTg0ZDliMzViNzI3YSIsInRpZCI6IjFiYmM4YTM5LTRiMWEtNGFkOC05MDJlLTJkNDhjZDE4MTBiYiIsInV0aSI6IjFPM1pyVUhoclVDTldPNy1TMXdLQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfZnRkIjoidWZvakxyY0hKYUtibkFIRWVQd04yLXJMbHNEODBEZFh3ZDV4VXpuOGgwY0JZWE5wWVhOdmRYUm9aV0Z6ZEMxa2MyMXoifQ.Vbfe9Vi601xKgqdCWXVQdbBYhXmMI8-pF4PLAX12zf1SIL535Px_l-CQI2lFSY3EsLyj0qOsRaWohOo0L5zx7AemdtVXeEXgj2e2riXGfZrMZLKhB7i7omv86rcwc9Ub2JrHGJgKs-cU5AF9iqY6OT3xIt3oQ_Ew0gFFSxGDZhYGl1OJyDPgIu0Jqo8uwN6i_FnBVQ66WVryhqYclREiyxDF-dahVFfDEc8_t3D9EIqpbkuYuVAMrITLxECg5nVmIF_3H-eo23_hEKNB19E522wJ4tOwH5QUFDMvNcVe-BiSGXRrNOInt2FACcUE3ZL0SOXAyqhJslTFxzLnqnEHZg"

if [[ -z "$SUBSCRIPTION_ID" || -z "$RESOURCE_GROUP_NAME" || -z "$LOCATION" || -z "$BEARER_TOKEN" ]]; then
  echo "Usage: $0 <subscription-id> <resource-group-name> <location> <bearer-token>"
  exit 1
fi

API_VERSION="2021-04-01"
URL="https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/resourcegroups/${RESOURCE_GROUP_NAME}?api-version=${API_VERSION}"

# JSON body
BODY=$(cat <<EOF
{
  "location": "$LOCATION"
}
EOF
)

echo "Creating Resource Group: $RESOURCE_GROUP_NAME in $LOCATION"

curl -X PUT "$URL" \
  -H "Authorization: Bearer $BEARER_TOKEN" \
  -H "Content-Type: application/json" \
  -d "$BODY"
